<?php
#######################################
####### Spacesim Game Settings #######
#######################################

## ATTENTION ##
## DO NOT EDIT THIS FILE ##
## You can redefine settings in your constants.php file ##

# How far in the future the game is set
if(!defined('SSIM_YEAR')) define('SSIM_YEAR', 223);

# Base fuel price per unit, in credits
if(!defined('SSIM_FUEL_BASE_COST')) define('SSIM_FUEL_BASE_COST', 500);

# The legal rating for newly created pilots
if(!defined('SSIM_STARTING_LEGAL')) define('SSIM_STARTING_LEGAL', 100);

# How many credits new pilots start with
if(!defined('SSIM_STARTING_CREDITS')) define('SSIM_STARTING_CREDITS', 25000);

