<?php

define('SSIM_VERSION_PATCH',0);
define('SSIM_VERSION_MINOR',1);
define('SSIM_VERSION_MAJOR',0);
define('SSIM_VERSION_TAG','-dev');

define('SSIM_VERSION',SSIM_VERSION_MAJOR.'.'.SSIM_VERSION_MINOR.'.'.SSIM_VERSION_PATCH.SSIM_VERSION_TAG);